@startuml
participant "CPU" as cpu
participant "SEC" as sec
participant "PEI" as pei
participant "DXE" as dxe
participant "BDS" as bds
participant "Windows" as os

cpu --> sec: Encender
sec --> pei: Memoria cache lista
pei --> dxe: RAM disponible
dxe --> bds: Drivers cargados
bds --> os: Bootea el SO
@enduml
